### ISSUE TITLE
Redmine 2.5 and uninitialized constant RAILS_ENV

### ISSUE THREAD

**Issue by leventyalcin** [waj/redmine_google_apps#13]
Everything is OK when I remove this plugin and that's all I know 

```
/home/redmine/redmine/plugins/redmine_google_apps/init.rb:3:in `<top (required)>': uninitialized constant RAILS_ENV (NameError)
    from /home/redmine/redmine/lib/redmine/plugin.rb:133:in `block in load'
    from /home/redmine/redmine/lib/redmine/plugin.rb:124:in `each'
    from /home/redmine/redmine/lib/redmine/plugin.rb:124:in `load'
    from /home/redmine/redmine/config/initializers/30-redmine.rb:19:in `<top (required)>'
    from /var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
    from /var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/engine.rb:592:in `each'
    from /var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/engine.rb:592:in `block in <class:Engine>'
    from /var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `instance_exec'
    from /var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `run'
    from /var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `each'
    from /var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `run_initializers'
    from /var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/application.rb:136:in `initialize!'
    from /var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /home/redmine/redmine/config/environment.rb:14:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/redmine/redmine/config.ru:3:in `block in <main>'
    from /usr/lib/ruby/vendor_ruby/rack/builder.rb:51:in `instance_eval'
    from /usr/lib/ruby/vendor_ruby/rack/builder.rb:51:in `initialize'
    from /home/redmine/redmine/config.ru:1:in `new'
    from /home/redmine/redmine/config.ru:1:in `<main>'
    from /usr/lib/ruby/vendor_ruby/rack/adapter/loader.rb:36:in `eval'
    from /usr/lib/ruby/vendor_ruby/rack/adapter/loader.rb:36:in `load'
    from /usr/lib/ruby/vendor_ruby/rack/adapter/loader.rb:45:in `for'
    from /usr/lib/ruby/vendor_ruby/thin/controllers/controller.rb:169:in `load_adapter'
    from /usr/lib/ruby/vendor_ruby/thin/controllers/controller.rb:73:in `start'
    from /usr/lib/ruby/vendor_ruby/thin/runner.rb:185:in `run_command'
    from /usr/lib/ruby/vendor_ruby/thin/runner.rb:151:in `run!'
    from /usr/bin/thin:6:in `<main>'
```

**Comment by patwcummins** [comment]
Edit the init.rb and change RAILS_ENV to ENV["RAILS_ENV"].  However.. this plugin doesn't appear to work with 2.x
