### ISSUE TITLE
Admin menu error - No route matches

### ISSUE THREAD

**Issue by jacquesbh** [waj/redmine_google_apps#6]
Hi,

I've an error after installing your plugin.
If I comment the line #17 of init.rb I can go in admin, but impossible to access the plugin configuration page...

Thanks,

(Redmine 1.3.1.devel)

```
Processing AdminController#plugins (for 82.127.47.85 at 2012-02-17 19:34:10) [GET]
  Parameters: {"action"=>"plugins", "controller"=>"admin"}
  SQL (0.1ms)   SELECT max(`settings`.updated_on) AS max_updated_on FROM `settings` 
  User Load (0.1ms)   SELECT * FROM `users` WHERE (`users`.`id` = 3) AND (users.status = 1) AND ( (`users`.`type` = 'User' OR `users`.`type` = 'AnonymousUser' ) ) 
Rendering template within layouts/admin
Rendering admin/plugins

ActionView::TemplateError (No route matches {:controller=>"google_apps", :action=>"admin"}) on line #3 of app/views/admin/_menu.html.erb:
1: <div id="admin-menu">
2:   <ul>
3:     <%= render_menu :admin_menu %>
4:   </ul>
5: </div>

    lib/redmine/menu_manager.rb:150:in `render_single_menu_node'
    lib/redmine/menu_manager.rb:102:in `render_menu_node'
    lib/redmine/menu_manager.rb:91:in `render_menu'
    lib/redmine/menu_manager.rb:168:in `menu_items_for'
    lib/redmine/menu_manager.rb:165:in `each'
    lib/redmine/menu_manager.rb:165:in `menu_items_for'
    lib/redmine/menu_manager.rb:90:in `render_menu'
    app/views/admin/_menu.html.erb:3
    app/views/layouts/admin.html.erb:4
    app/helpers/application_helper.rb:1023:in `content_for'
    app/views/layouts/admin.html.erb:2
    /usr/lib/ruby/1.8/phusion_passenger/rack/request_handler.rb:92:in `process_request'
    /usr/lib/ruby/1.8/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
    /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:418:in `start_request_handler'
    /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:358:in `handle_spawn_application'
    /usr/lib/ruby/1.8/phusion_passenger/utils.rb:184:in `safe_fork'
    /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:354:in `handle_spawn_application'
    /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `__send__'
    /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `main_loop'
    /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
    /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:163:in `start'
    /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:213:in `start'
    /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:262:in `spawn_rails_application'
    /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:126:in `lookup_or_add'
    /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:256:in `spawn_rails_application'
    /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:80:in `synchronize'
    /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
    /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:255:in `spawn_rails_application'
    /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:154:in `spawn_application'
    /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:287:in `handle_spawn_application'
    /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `__send__'
    /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `main_loop'
    /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
    /usr/lib/phusion_passenger/passenger-spawn-server:61

Rendering /usr/share/redmine/public/500.html (500 Internal Server Error)
```

**Comment by jacquesbh** [comment]
No idea for fix this issue ? :)

**Comment by GeekTantra** [comment]
Found a fix:
1. Change `vendor/plugins/google_apps/app/controllers/google_apps_controller.rb`
   
    Remove line containing require 'gapps_openid'
   
   ```
   diff --git a/app/controllers/google_apps_controller.rb b/app/controllers/google_apps_controller.rb
   index 4ac1f7c..ca7aaa0 100644
   --- a/app/controllers/google_apps_controller.rb
   +++ b/app/controllers/google_apps_controller.rb
   @@ -1,4 +1,4 @@
   -require 'gapps_openid'
   +#require 'gapps_openid'
   ```
2. Add a file `vendor/plugins/google_apps/config/routes.rb` with the following contents:
   
   ```
   ActionController::Routing::Routes.draw do |map|
     map.connect 'admin/plugins/google_apps/:action', :controller => 'google_apps', :conditions => {:method => [:post, :get]}
   end
   ```
3. Download http://svn.ohwr.org/ohr-support/trunk/lib/tabular_form_builder.rb to `vendor/plugins/google_apps/lib/`
   
   ```
   cd vendor/plugins/google_apps/lib/ && wget -c http://svn.ohwr.org/ohr-support/trunk/lib/tabular_form_builder.rb
   ```

After making these changes the plugin started working.

Note: You would need to setup OpenID discovery vanity URL by following this guide: http://jeremiahlee.com/blog/2009/09/28/how-to-setup-openid-with-google-apps/

**Comment by shahul001** [comment]
Hi

I have migrated the Google Apps login plugin to redmine 1.4.0, and got  above error but resolved it by following the steps  and migrated successfully  but when i am taking the google_apps tab in Administration-Google_apps its showing error likes this:

ActionView::TemplateError (uninitialized constant ActionView::Base::CompiledTemplates::TabularFormBuilder) on line #3 of vendor/plugins/google_apps/plugins/google_apps/app/views/google_apps/add.rhtml:
1: <h2><%= link_to 'Google Apps', :controller => 'google_apps', :action => 'admin' %> &#187; New domain</h2>
2:
3: <% form_for :domain, :builder => TabularFormBuilder do |f| -%>
4: <div class="box tabular">
5:   <p><%= f.text_field :name, :label => :field_name %></p>
6: </div>

```
vendor/plugins/google_apps/plugins/google_apps/app/views/google_apps/add.rhtml:3:in `_run_rhtml_vendor47plugins47google_apps47plugins47google_apps47app47views47google_apps47add46rhtml'
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/usr/local/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:95:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `each'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:23:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:82:in `start'
```

Rendering /home/redmine/redmine-1.4.0/public/500.html (500 Internal Server Error)
Please help me its urgent

**Comment by GeekTantra** [comment]
I have tried the fixed plugin at https://github.com/nettantra/redmine_google_apps with Redmine 1.4.0, it seems to work properly. Please check the other plugins which are installed which might be conflicting with this one.

**Comment by shahul001** [comment]
Hi

Thanks very much ,i have successfully installed the plug in

But also facing another issue,When I enter in the appropriate authentication and then select to login.I am redirected to the redmine page and receiving the error like "OpenID verification failed"

Here is my production log:
Error attempting to use stored discovery information: OpenID::TypeURIMismatch
Attempting discovery to verify endpoint

Thanks

**Comment by shahul001** [comment]
Hi

Please help me, My upgrade is stopped due to this issue

**Comment by GeekTantra** [comment]
Please follow the link mentioned in the the issue note i.e.

> Note: You would need to setup OpenID discovery vanity URL by following this guide:
> http://jeremiahlee.com/blog/2009/09/28/how-to-setup-openid-with-google-apps/

**Comment by shahul001** [comment]
Hi

I don't know to setup the openid with google_apps,  so please help me

**Comment by GeekTantra** [comment]
Please follow this link: http://jeremiahlee.com/blog/2009/09/28/how-to-setup-openid-with-google-apps/

**Comment by shahul001** [comment]
Hi

No improvement, but i have one question

In redmine-1.3.2 i have migrated  the plugin without any issue and not  followed the above link  but in redmine-1.4 i am facing this problem what was the issue? and also i would be great if it is  integrate the openid with  the google_apps plugin ,so that i would make things more easier

Thanks

**Comment by zamkp** [comment]
Hi

I'm trying to upgrade my redmine from 1.3.0 to 2.0.0, but i have problems with the database migration, when i run the command : rake db:migrate RAILS_ENV=production

its showing an error like
rake aborted!
uninitialized constant RAILS_ENV

MY ERROR LOG IS:

ActiveRecord::SubclassNotFound (The single-table inheritance mechanism failed to locate the subclass: 'GoogleAppsAuthSource'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite AuthSource.inheritance_column to use another column for that information.):
app/models/user.rb:139:in `try_to_login'
app/controllers/account_controller.rb:143:in`password_authentication'
app/controllers/account_controller.rb:138:in `authenticate_user'
app/controllers/account_controller.rb:30:in`login'

Here is the list of plugin that i am using in my old redmine:
1)Google Apps plugin

2)Redmine Code Review plugin

3)Redmine Hudson plugin
