### ISSUE TITLE
ActionView::TemplateError (uninitialized constant ActionView::Base::CompiledTemplates::TabularFormBuilder) on line #3 of vendor/plugins/google_apps/plugins/google_apps/app/views/google_apps/add.rhtml

### ISSUE THREAD

**Issue by shahul001** [waj/redmine_google_apps#9]
Hi

I have migrated the Google Apps login plugin to redmine 1.4.0, migration process works successfully but but when i am taking the google_apps tab in Administration-Google_apps  its showing error likes this:

ActionView::TemplateError (uninitialized constant ActionView::Base::CompiledTemplates::TabularFormBuilder) on line #3 of vendor/plugins/google_apps/plugins/google_apps/app/views/google_apps/add.rhtml:
1: <h2><%= link_to 'Google Apps', :controller => 'google_apps', :action => 'admin' %> &#187; New domain</h2>
2: 
3: <% form_for :domain, :builder => TabularFormBuilder do |f| -%>
4: <div class="box tabular">
5:   <p><%= f.text_field :name, :label => :field_name %></p>
6: </div>

```
vendor/plugins/google_apps/plugins/google_apps/app/views/google_apps/add.rhtml:3:in `_run_rhtml_vendor47plugins47google_apps47plugins47google_apps47app47views47google_apps47add46rhtml'
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/usr/local/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:95:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `each'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:23:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:82:in `start'
```

Rendering /home/redmine/redmine-1.4.0/public/500.html (500 Internal Server Error)

Please help me, I cant complete my migration

Thanks
Shahul

**Comment by shahul001** [comment]
Here is my error Log
ActionView::TemplateError (uninitialized constant ActionView::Base::CompiledTemplates::TabularFormBuilder) on line #3 of vendor/plugins/google_apps/plugins/google_apps/app/views/google_apps/add.rhtml:
1: <h2><%= link_to 'Google Apps', :controller => 'google_apps', :action => 'admin' %> &#187; New domain</h2>
2:
3: <% form_for :domain, :builder => TabularFormBuilder do |f| -%>
4: <div class="box tabular">
5:   <p><%= f.text_field :name, :label => :field_name %></p>
6: </div>

```
vendor/plugins/google_apps/plugins/google_apps/app/views/google_apps/add.rhtml:3:in `_run_rhtml_vendor47plugins47google_apps47plugins47google_apps47app47views47google_apps47add46rhtml'
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/usr/local/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:95:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `each'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:23:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:82:in `start'
```

Rendering /home/redmine/redmine-1.4.0/public/500.html (500 Internal Server Error)
